---
# Exercise: use chrony as NTP client and configure with upstream server of choice

- name: Chrony configuration.
  gather_facts: true                                # Standaard configuratie is 'true'
  hosts: howest_proxmox                             # Proxmox 7 servers - remote lab

  handlers:
  - name: reload sources
    ansible.builtin.command: /usr/bin/chronyc reload sources

  - name: restart chronyd
    ansible.builtin.service:
      name: chronyd.sources
      state: restarted

  tasks:
  - name: Ensure chrony is installed.
    ansible.builtin.package:
      name: chrony
      state: present

  - name: Make use of upstream NTP server.
    block:
    - name: Show chosen NTP server.
      ansible.builtin.debug:
        msg: "NTP server will be {{ ntp_server }}."

    - name: Add time source.
      ansible.builtin.copy:
        content: |
          server {{ ntp_server }} iburst
        dest: /etc/chrony/sources.d/local.sources
        owner: root
        group: root
        mode: '0644'
      notify: reload sources

    # Current line and lines that look like
    # pool 2.debian.pool.ntp.org iburst
    # Should be commented
    # So, everything that startes with 'pool' or 'server'
    - name: Ensure no existing time sources are present.
      ansible.builtin.replace:
        path: /etc/chrony/chrony.conf
        regexp: '^(server.+|pool.+)$'
        replace: '# \1'
        backup: true
      notify: restart chronyd 
    when: ntp_server is defined

  - name: Ensure chrony is enabled.
    ansible.builtin.service:
      name: chronyd.service
      enabled: true                                 # Enable at boot
      state: started                                # Ensure chrony is running now
