---
# Exercise: add chrony and configure with NTP server of choice
- name: Chrony configuration.
  gather_facts: true                                # Standaard configuratie is 'true'
  hosts: howest_proxmox:!panoramix.snwb.howest.be   # Proxmox 7 servers - remote lab
  vars:
    ntp_server: ntp.telenet.be

  handlers:
  - name: reload sources
    ansible.builtin.command: /usr/bin/chronyc reload sources

  tasks:
  - name: Ensure chrony is installed.
    ansible.builtin.package:
      name: chrony
      state: present

  - name: Show chosen NTP server.
    ansible.builtin.debug:
      msg: "NTP server will be {{ ntp_server }}."

  - name: Add time source.
    ansible.builtin.copy:
      content: |
        server {{ ntp_server }} iburst
      dest: /etc/chrony/sources.d/local.sources
      owner: root
      group: root
      mode: '0644'
    notify: reload sources

  - name: Ensure chrony is enabled.
    ansible.builtin.service:
      name: chronyd.service
      enabled: true                                 # Enable at boot
      state: started                                # Ensure chrony is running now

# TODO: Chrony should use a specific server
# - herstarten van chrony is NIET nodig, enkel commando 'chronyc reload sources' uitvoeren
